=== aws-samples/private-marketplace-automation/configuration_files/pmp_automation_json_schema.json
{
  "$schema": "http://json-schema.org/draft-pmp-2024/schema#",
  "type": "object",
  "properties": {
    "Name": {
      "type": "string",
      "description": "Experience name"
    },
    "AssociatePrincipals": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "description": "Principal to associate to an experience. Principals can be org-id, ou-id, or AWS account id."
        }
      ]
    },
    "DisassociatePrincipals": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "description": "Principal to disassociate from an experience. Principals can be org-id, ou-id, or AWS account id."
        }
      ]
    },
    "AllowProducts": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "description": "Product ids of AWS Marketplace products to allow for procurement."
        }
      ]
    },
    "DenyProducts": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "description": "Product ids of AWS Marketplace products to deny from procurement."
        }
      ]
    },
    "Status": { 
      "enum": ["Enabled", "Disabled"],
      "description": "Specify status of experience." 
    },
    "PolicyResourceRequests": { 
      "enum": ["Allow", "Deny"],
      "description": "Specify whether end users are allowed to make software requests."
    }
  }
}

=== aws-samples/private-marketplace-automation/configuration_files/Experience_Default#1_0.json
{
    "Name": "Default Experience",
    "AssociatePrincipals": [
        "o-abcdef1234"
    ],
    "AllowProducts":[
        "12345678-0123-4567-abcd-43176543210",
        "12345678-0123-4567-abcd-43176543211"
    ],
    "DenyProducts":[
        "12345678-0123-4567-abcd-43176543212"
    ],
    "Status": "Enabled",
    "PolicyResourceRequests": "Deny"
}
